# Generated by Django 6.0.2 on 2026-03-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.category'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(related_name='reviews', to='product.product'),
        ),
    ]
